### ISSUE TITLE
Wazuh packages redesign tier 2 - Migrate and adapt Wazuh Unattended Scripts

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-installation-assistant#1]
## Description 
The Wazuh unattended scripts should be migrated from the `wazuh-packages` repository to this one for 4.9.0.
The repository structure must be defined with this code migration.

The tasks listed below are extracted from https://github.com/wazuh/internal-devel-requests/issues/718. Use that issue for additional information and requirements.

## Tasks
- [ ] Migrate the Wazuh installation assistant code into this repository
- [ ] Automate artifact generation through CI using GHA
- [ ] Add secrets to GH (to upload packages to S3)
- [ ] Add CI testing (AIO and Distributed) for the Wazuh installation assistant
- [ ] Upload packages to S3 through CI

**Comment by davidjiglesias** [comment]
We have decided not to do this as part of this objective.
