### ISSUE TITLE
Workflow Python install error

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-installation-assistant#109]
# Description

We need to change the pip install commands due to an error with a new version of Python.

In other teams they advanced on a fix with `venv` in python, we must analyze that fix to be able to apply it in our workflows

## Tasks
- [x] Investigate the fix.
- [x] Do the necessary tests.
- [x] Implement the fix in the other workflows that use Python

> [!NOTE]  
> Another workaround is to use the Python version that works (3.10). For that, there is a Github Action in the Marketplace called [setup-python](https://github.com/actions/setup-python). We have to consider it as an option if the using of the Python venv gets complex.

**Comment by Enaraque** [comment]
# Update report

It is necessary to implement the `venv` in 2 workflows:
- [Test_installation_assistant](https://github.com/wazuh/wazuh-installation-assistant/blob/4.10.1/.github/workflows/Test_installation_assistant.yml)
- [Test_installation_assistant_distributed](https://github.com/wazuh/wazuh-installation-assistant/blob/4.10.1/.github/workflows/Test_installation_assistant_distributed.yml)

At the moment we have been able to successfully implement the `venv` in `Test_installation_assistant`.

It still needs to be implemented in `Test_installation_assistant_distributed`.

## Testing

We can see the execution of the Test_installation_assistant` that ends succesfully:
- https://github.com/wazuh/wazuh-installation-assistant/actions/runs/11669113874/job/32490341393
