### ISSUE TITLE
Support new stage Alpha 2 for 4.10.0 in wazuh-installation-assistant repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-installation-assistant#116]
## Description

This issue attempts to support a new stage Alpha 2 for 4.10.0 in the wazuh-installation-assistant repository.

## Tasks

- [ ] Delete previous Alpha 2 release: https://github.com/wazuh/wazuh-installation-assistant/releases/tag/v4.10.0-alpha2.
- [ ] Delete previous v4.10.0-alpha2 tag.
- [ ] Ensure changelog is updated for 4.10.0 (if applicable).
- [ ] Bump revision for branch 4.10.0 on wazuh-installation-assistant repository.
- [ ] Change `source_branch` to tag v4.10.0-alpha2 in branch 4.10.0
- [ ] Create tag v4.10.0-alpha2 from branch 4.10.0 on wazuh-installation-assistant repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-installation-assistant/releases/tag/v4.10.0-alpha2.
- [ ] Change `source_branch` back to 4.10.0 in branch 4.10.0
