### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh-installation-assistant repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-installation-assistant#125]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh-installation-assistant repository.

## Tasks

- [ ] Delete previous Alpha 2 release: https://github.com/wazuh/wazuh-installation-assistant/releases/tag/v4.10.0-alpha2.
- [ ] Delete previous v4.10.0-alpha2 tag.
- [ ] Ensure changelog is updated for 4.9.2 (if applicable).
- [ ] Bump revision for branch 4.9.2 on wazuh-installation-assistant repository.
- [ ] Change `source_branch` to tag v4.9.2-rc1 in branch 4.9.2
- [ ] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh-installation-assistant repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-installation-assistant/releases/tag/v4.9.2-rc1.
- [ ] Change `source_branch` back to 4.9.2 in branch 4.9.2
