### ISSUE TITLE
Support new stage Alpha 3 for 4.9.0 in wazuh-installation-assistant repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-installation-assistant#14]
## Description

This issue attempts to support a new stage Alpha 3 for 4.9.0 in the wazuh-installation-assistant repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh-installation-assistant repository.
- [ ] Create tag v4.9.0-alpha3 from branch 4.9.0 on wazuh-installation-assistant repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-installation-assistant/releases/tag/v4.9.0-alpha3.

**Comment by davidcr01** [comment]
This repository is not being used yet.
