### ISSUE TITLE
Update GitHub Actions to v4

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-installation-assistant#159]
## Description
We need to update the GH Actions `actions/upload-artifact` and `actions/download-artifact` to `v4`.
It was found that `v3` is being used in these workflows:
- https://github.com/wazuh/wazuh-installation-assistant/blob/4.10.1/.github/workflows/offline-installation.yml
- https://github.com/wazuh/wazuh-installation-assistant/blob/4.10.1/.github/workflows/password-tool.yml
- https://github.com/wazuh/wazuh-installation-assistant/blob/4.10.1/.github/workflows/Test_installation_assistant_distributed.yml
- https://github.com/wazuh/wazuh-installation-assistant/blob/4.10.1/.github/workflows/Test_installation_assistant.yml

## Tasks
- [x] Update the version to `v4`
- [x] Test the workflows
- [x] Provide evidence of a successful execution

**Comment by Enaraque** [comment]
The corresponding changes have been made to the workflows that were using version v3.

>[!IMPORTANT]
> During testing, some errors were detected that prevent the workflow from running entirely, and therefore, verifying that it works correctly with these changes.
> - https://github.com/wazuh/wazuh-installation-assistant/issues/161
> - https://github.com/wazuh/wazuh-installation-assistant/issues/162
>
> Due to this problems, the issue is now blocked
