### ISSUE TITLE
Update the GitHub runners image from latest to ubuntu-22.04 in installation assistant workflows

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-installation-assistant#165]
## Description

Due to the updates that the `latest` images of GitHub runners undergo, we must set a fixed image to avoid failures in our workflows due to updates in the mentioned image.
It is recommended to define the image `ubuntu-22.04`

## Tasks

- [x] Test_installation_assistant.yml
- [x] Test_installation_assistant_distributed.yml
- [x] builder_installation_assistant.yml
- [x] offline-installation.yml
- [x] password-tool.yml

## Issue related

https://github.com/wazuh/internal-devel-requests/issues/1890

**Comment by CarlosALgit** [comment]
## Update Report

I've changed the Linux images to `ubuntu-22.04` but when testing the workflows there are some errors that have to be studied yet.

**Comment by CarlosALgit** [comment]
## Update Report

The issue status is the following:

- ✅ Test Installation Assistant [here](https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12412379480).
-  ✅ Test Installation Assistant distributed [here](https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12413063840).
-  ✅ Installation Assistant build [here](https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12396614774).
 - ❌ Offline Installation here (this script is broken right now and we are working in the fix in https://github.com/wazuh/wazuh-installation-assistant/issues/161. So this one remains blocked).
- ⚠️ Passwords tool (this workflow only runs when changing files in the passwords-tool directory and cant be run pointing to this branch because it look for packages of 4.10.3 that we do not have. Another sucessfully run can be seen [here](https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12396215542?pr=170). This workflow run uses ubuntu-latest but when it was ran ubuntu-latest image corresponded to ubuntu-22.04 Also, this workflow suffered a fix tracked in https://github.com/wazuh/wazuh-installation-assistant/issues/162).

**Comment by CarlosALgit** [comment]
## Update Report

I will have to open the PR again because it closed due to the branch maintenance.

**Comment by CarlosALgit** [comment]
## Update Report

I will remove the blocked status because the workflow is only for testing purposes. The workflow will be tested in this issue https://github.com/wazuh/wazuh-installation-assistant/issues/161 but it should work right as the `ubuntu-latest` image is `ubuntu-22.04` still and we are making this change as preventive.
