### ISSUE TITLE
Migrate the Installation assistant test pipelines to GHA

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-installation-assistant#20]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description
Because of the `Wazuh packages redesign tier 2` objective we need to migrate the Wazuh installation assistant pipeline (`Test_unattended_distributed`, `Test_unattended_distributed_cases`, `Test_unattended` and `Test_unattended_tier`) to GHA.

## Tasks
- [x] Adapt pytests
- [x] Migrate all the Wazuh installation assistant test pipelines from Jenkins to GHA:
    - [x] `Test_unattended_distributed`
    - [ ] ~~`Test_unattended_distributed_cases`~~
    - [x] `Test_unattended`
    - [x] `Test_unattended_tier`
- [x] Modify the name of the GHA from `unattended_installer` to `installation_assistant` if applies
- [x] Validate the GHA work as expected

## Related
- https://github.com/wazuh/wazuh-installation-assistant/issues/21

**Comment by davidcr01** [comment]
# Update Report

## Investigation

I have been investigating the mentioned Jenkins pipeline, and we decided to migrate the `Test_unattended`, `Test_unattended_tier` and `Test_unattended_distributed` pipelines.

Related to the rest of the tests:
- `Test_unattended_distributed_cases`: The scope of this pipeline is to test the distributed installation with the installation assistant, but some components are installed in one machine and some components in another machine. For example: 
  - Instance A = indexer and manager. Instance B = dashboard. 
  - Instance A = manager and manager. Instance B = indexer and dashboard. 
  - Instance A = manager and dashboard. Instance B = indexer.
We think that these cases are tested and reproduced in the `Test_unattended_distributed` pipeline and we discard migrating it, as it is covered in the mentioned pipeline.

**Comment by davidcr01** [comment]
# Update Report

- [x] Header of `Test_installation_assistant.yml` (in replacement of the `Test_unattended` Jenkins pipeline.
- [x] Header of `Test_installation_assistant_tier.yml` (in replacement of the `Test_unattended_tier` Jenkins pipeline.
  - As GHA does not support multiple choice (related: https://github.com/actions/runner/issues/2076), the multiple OS must be managed with a list of checkboxes.
- [x] Header of `Test_installation_assistant_distributed.yml` (in replacement of the `Test_unattended_distributed` Jenkins pipeline.

**Comment by davidcr01** [comment]
# Update Report

## Test installation assistant workflow

- [x] The first steps of this workflow have been developed and tested:
- [x] Input parameters visualization
- [x] Composite name variable manage
- [x] Ansible installation
- [x] Allocation module clone and installation
- [x] Allocation instance provision and deletion

These steps have been tested here: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10576987236/job/29303972255

**Comment by davidcr01** [comment]
## Update Report

:warning: I encountered a severe problem related to the Ansible version and the usage of the Ansible modules. In my case, many Ansible playbooks necessary to complete the GHA use Ansible modules, such as the [YUM module](https://docs.ansible.com/ansible/9/collections/ansible/builtin/yum_module.html) and the [APT module](https://docs.ansible.com/ansible/9/collections/ansible/builtin/apt_module.html).

The problem was that, in case of Amazon Linux 2, the package manager could not be fetched, and then, the YUM module could not be used, because internally it used the package manager variable (a variable that defines which package manager uses the system):
```console
fatal: [ec2-44-212-66-219.compute-1.amazonaws.com]: FAILED! => {"changed": false, "msg": "Could not find a matching action for the \"unknown\" package manager."}
```
> [!CAUTION]
> The YUM and the APT modules were not the only ones affected. Some Ansible variables such as the `ansible_os_family` and the `ansible_os_distribution` could not be used. This is a huge problem in this case because the majority of playbooks are prepared to be executed in many systems, and this is controlled with this kind of variables.

After many failed attempts to solve this, the provisional solution I came up with was installing a specific version of Ansible core. The mentioned problem was provoked with the deprecation of the YUM module and YUM action here: https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst#removed-features-previously-deprecated. Then, the approach was to change the Ansible installation in the GH runner. See [this](https://github.com/wazuh/wazuh-installation-assistant/commit/08b193eb9c7a6e8a30c1e87f325cb0d96c3d5eea) commit.

:heavy_check_mark: Now, Ansible is installed using `pip`, a tool recommended by the official documentation:
```yaml
- name: Install Ansible
  run: sudo apt-get update && sudo apt install -y python3 && python3 -m pip install --user ansible-core==2.16
```

With this change, the two use cases (running in Ubuntu 22 and running in AL2) succeeded:
- Ubuntu22: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10597400939/job/29367471820
- AL2: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10597398480/job/29367464092

> [!WARNING]
> We are aware that installing a specific version of Ansible core is not the best solution because we highly depend on that version. However, due to the migration's urgency, we will take this approach as a provisional solution until we find a better solution or, on the other hand, we may rework these GHAs in 5.0.

**Comment by davidcr01** [comment]
On hold due to: https://github.com/wazuh/wazuh-installation-assistant/issues/44

**Comment by davidcr01** [comment]
# Update Report

## Problem with Allocator VM deletion

I encountered a problem when setting the final conditional of the Allocator VM deletion. The original task was:
```yml
- name: Delete allocated VM
  if: always() && steps.allocator_instance.outcome == 'success' && inputs.DESTROY == 'true'
  run: python3 wazuh-automation/deployability/modules/allocation/main.py --action delete --track-output /tmp/allocator_instance/track.yml
```
This task was always not executed. After many hours debugging, I found that the `inputs.DESTROY == 'true'` condition was the problem:
- In the workflow, the `DESTROY` input is a boolean parameter.
- When evaluating a boolean parameter as a string, the result is `NaN`
- Then, the condition was always false.

:heavy_check_mark: Changing `inputs.DESTROY == 'true'` by `inputs.DESTROY == true` solved the problem.

Here I have tested with the condition that I have passed the possible scenarios that have occurred to me:

- Fails and has to delete: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10663953470
- Fails and does not have to delete (`DESTROY` not marked): https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10664116674/job/29554732442

Cancelation cases:
- Has to delete (`DESTROY` marked): https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10664234057/job/29555093143 X
- Does not have to delete (`DESTROY` not marked): https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10664293853/job/29555275236
- Does not have to delete it because the machine hasn't been provisioned: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10664221289/job/29555055235

**Comment by davidcr01** [comment]
# Update Report

## Progresses

### Allocator VM upload

I have developed the upload artifact logic with the following code:
```yml
- name: Compress Allocator directory
  id: compress_allocator_files
  if: always() && steps.allocator_instance.outcome == 'success' && inputs.DESTROY == false
  run: |
    zip -P "${{ secrets.ZIP_ARTIFACTS_PASSWORD }}" -r $ALLOCATOR_PATH.zip $ALLOCATOR_PATH
  
- name: Upload Allocator directory as artifact
  if: always() && steps.compress_allocator_files.outcome == 'success' && inputs.DESTROY == false
  uses: actions/upload-artifact@v4
  with:
    name: allocator-instance
    path: ${{ env.ALLOCATOR_PATH }}.zip
``` 

The new development was tested:
- The artifact is uploaded and the VM is not destroyed with the `DESTROY` option unmarked: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10668302353
- The artifact is not uploaded and the VM is destroyed with the `DESTROY` option marked: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10668298933/job/29567689207

### SSH connection problem
The SSH connection problem was solved by modifying the Ansible playbook. It seems that, if the playbook takes a considerable time to execute, Ansible closes the connection. This was solved with the following code:
```yml
- name: Install assistant installer
  command: "bash {{ script_name }} -a -v"
  args:
    chdir: "{{ script_path }}"
  register: install_results
  async: 500
  poll: 5
```

The new development was tested in the OSs where the playbooks was failing:
- :heavy_check_mark: Ubuntu 22: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10666638811
- :heavy_check_mark: RHEL7: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10666641565
- :heavy_check_mark: CentOS 8: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10666877999

**Comment by davidcr01** [comment]
# Update Report

## Ubuntu 20 problem :heavy_check_mark: 

As the Python 3.9 version was only being installed in Ubuntu Jammy (22.04) and the repository to install Python 3.9 was being added in every Ubuntu distribution, I changed the conditional of the repository addition to be only added in Ubuntu Jammy. These tasks were grouped in a `block`. Now, the GHA passes successfully: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10678513202/job/29595709184

## Ubuntu 18 problem :heavy_check_mark: 

Ubuntu 18 (Bionic) presented another problem related to pip installation:
```console
"ERROR: This script does not work on Python 3.6. The minimum supported Python version is 3.8. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.", "stdout_lines": ["ERROR: This script does not work on Python 3.6. The minimum supported Python version is 3.8. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead."
```
Then, I tried to change the link as the error mentioned and the result was another error:
```console
root@ip-172-31-85-170:/home/ubuntu# curl  https://bootstrap.pypa.io/pip/3.6/get-pip.py | python3 -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2108k  100 2108k    0     0  39.6M      0 --:--:-- --:--:-- --:--:-- 39.6M
Traceback (most recent call last):
  File "<stdin>", line 27079, in <module>
  File "<stdin>", line 137, in main
  File "<stdin>", line 113, in bootstrap
  File "<stdin>", line 94, in monkeypatch_for_cert
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/cli/base_command.py", line 13, in <module>
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/cli/cmdoptions.py", line 23, in <module>
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/configuration.py", line 26, in <module>
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/utils/logging.py", line 13, in <module>
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/utils/misc.py", line 40, in <module>
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/locations/__init__.py", line 14, in <module>
  File "/tmp/tmphpdgbd10/pip.zip/pip/_internal/locations/_distutils.py", line 9, in <module>
ModuleNotFoundError: No module named 'distutils.cmd'
```

Installing the `python3-pip` package with the package manager solved the problem. A new task was added to the provision playbook. Now, the GHA passed successfully: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10678513202/job/29595709184

## Ubuntu 16 problem

In Ubuntu 16, Python 3.6 is needed. Before, we could use the `deadsnake` repository, but this repository removed the support for Ubuntu 16: https://github.com/deadsnakes/issues/issues/195

**Comment by davidcr01** [comment]
# Update Report - Tier assistant test

I started to develop the tier of the assistant test. This worklfow will launch several runs of the assistant test workflow: https://github.com/wazuh/wazuh-installation-assistant/pull/46


Some things to highlight:

- The input parameters to choose the operating systems to test have been changed to a string parameter that accepts a list of numbers separated by commas. This has been due to the maximum limit of 10 parameters in the workflow form. To avoid errors when writing the names of the operating systems, they have been encoded, and instead of writing the names of the operating systems, the numbers associated with them are written.
- Several padding characters have had to be introduced in the description of the input parameter of the operating systems so that the encoding is easy to read, since the description parameter does not support any possible formatting (we tried with `\n` and with `<br>`)
- The blank spaces have had to be removed from the names of the operating systems since these caused problems when obtaining the operating systems associated with the numbers. This has impacted the `Test_installation_assistant.yml` workflow.

In a first test, the workflow has been executed correctly, parsing the operating systems and launching different instances of the assistant workflow: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10696903344/job/29653020167

This execution has launched the following executions:
- https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10696905745
- https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10696905822
- https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10696905874

> [!NOTE]
> The assistant test worklfows have failed because they are using a branch based on 4.10.0, and there are no 4.10.0 packages yet to install.

Now working on the tier waits the child runs.

**Comment by davidcr01** [comment]
After talking with the team leaders, we are going to change the approach. We want to test if it's possible to unify the `Test_unattended` and `Test_unattended_tier`, and make a single workflow. This workflow would launch several jobs. Each job would represent a selected OS. This avoids developing the tier workflow, which is a little bit difficult because of the management of the executing runs of the `Test_unattended` and the multiple GitHub API calls.

**Comment by davidcr01** [comment]
# Update Report

The `Test_installation_assistant.yml` workflow has been modified to launch multiple jobs depending on the selected OSs. By this way, we can unify the test and its tier in one unique workflow. This has been achieved by using the matrix strategy:

```yml
jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false    # If a job fails, the rest of jobs will not be cancelled
      matrix:
        system: ${{ fromJson(inputs.SYSTEMS) }}
```
Then, the steps given below will be executed in different jobs, where each job will execute the test with one of the selected OS.

**Comment by davidcr01** [comment]
# Update Report - Distributed

Currently working on the distributed pipeline migration.

**Comment by davidcr01** [comment]
# Update Report - Distributed

## Jenkins pipeline explanation

We have decided to rework the distributed pipeline. The Jenkins pipeline performed the following installation:
- It provided 10 instances, an instance per available OS.
- It created a big inventory and a big `config.yml` config file with every 
- On each instance, it installed the Wazuh indexer, manager and dashboard.
- When installing the Wazuh manager, one of the instances (CentOS7) was the master node of the Wazuh server cluster, and the rest of the instances installed worker nodes.

This is a weird scenario, where the distributed installation is being checked, but we think this is not a real scenario to test it. Instead, we want to rework this test, taking into account that this would be done in 5.0.0. Also, we are doing this in order to avoid the effort and time of the development it would take to migrate exactly the old Jenkins pipeline, when it seems not to be very practical.

## Possible workaround

The proposed solution is to rework this pipeline. If we want to test the distributed installation using the assistant, we will perform the steps given in the [Wazuh indexer,](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html), [Wazuh server](https://documentation.wazuh.com/current/installation-guide/wazuh-server/installation-assistant.html) and [Wazuh dashboard](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html) documentation in this kind of installation. The infrastructure would be the following:
- For each OS selected in the pipeline:
  - Three different instances will be deployed using the allocator.
  - The three instances will have the same OS installed.
  - In one of them, a Wazuh indexer node and Wazuh manager **master** node will be installed.
  - In one of them, a Wazuh indexer node and Wazuh manager **worker** node will be installed.
  - In one of them, a Wazuh indexer node, Wazuh manager **worker** node and the Wazuh dashboard will be installed.

> [!IMPORTANT]
> This scenario does not test the connectivity between instances of different OSs. We should review if we also want to test this scenario or not.

Thus, the workflow will be the following task:
- General provision of the runner: repositories clonation, Ansible installation, Allocator setup...
- Provides three instances using the allocator.
- Get the private IPs of the three instances. This will be done using the AWS CLI and the `describe-instances` option.
- Build an inventory with the information of the three instances. The inventory should have a variable, such as `node_type`, to identify which node will install the manager master node or the manager worker node.
- Generate a `config.yml` file with the instances information and generate the certificates using the assistant.
- Copy the certificates to the three instances.
- Perform the Wazuh indexer, Wazuh manager, and Wazuh dashboard installation conditionally (controlled by the inventory), including the Wazuh indexer cluster initialization.
- Test the installation with the Python test.

**Comment by davidcr01** [comment]
# Update Report - Distributed

## Wazuh server installation :heavy_check_mark: 

I finally developed a logic in which the Wazuh manager worker nodes wait to the Wazuh manager master node to be installed:

```yml
- name: Install Wazuh server on master
  block:
    - name: Install Wazuh server (Master)
      command: "bash {{ tmp_path }}/wazuh-install.sh -ws {{ inventory_hostname }} -v"
      register: wazuh
    
    - name: Save Wazuh installation log (Master)
      blockinfile:
        marker: ""
        path: "{{ test_dir }}/{{ test_name }}_{{ inventory_hostname }}.log"
        block: |
          {{ wazuh.stderr }}
          --------------------------------
          {{ wazuh.stdout }}
  when: hostvars[inventory_hostname].manager_type == 'master'
  
  - name: Install Wazuh server on worker nodes
  block:
    - name: Wait for Wazuh master to be ready on port {{ check_port }}
      wait_for:
        host: "{{ master_ip }}"
        port: "{{ check_port }}"
        delay: "{{ delay }}"
        timeout: 300
      when: hostvars[inventory_hostname].manager_type == 'worker'
      async: 500
      poll: 5
  
    - name: Install Wazuh server (Workers)
      command: "bash {{ tmp_path }}/wazuh-install.sh -ws {{ inventory_hostname }} -v"
      register: wazuh
```
Here, the workers make petitions to the API master node (port 55000), and when the port is opened and ready, the worker nodes start their installation

**Comment by davidcr01** [comment]
# Update Report - Distributed

## Random `remoted` error
The development of the pipeline is finished and it is working as expected: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10881208924

However, it seems that some jobs are failing because the Python test is detecting a cluster error in some tests. The error is `wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb`. For example: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/10880747600/job/30188237777

```console
fatal: [worker1]: FAILED! => changed=true 
  cmd:
  - python3
  - -m
  - pytest
  - --tb=long
  - test_installation_assistant.py
  - -v
  - -m
  - wazuh or indexer or indexer_cluster
  delta: '0:00:03.545409'
  end: '2024-09-16 09:18:06.362740'
  msg: non-zero return code
  rc: 1
  start: '2024-09-16 09:18:02.817331'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    ============================= test session starts ==============================
    platform linux -- Python 3.9.20, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3
    cachedir: .pytest_cache
    rootdir: /tmp/test/tests/install, configfile: pytest.ini
    collecting ... collected 22 items / 5 deselected / 17 selected
  
    test_installation_assistant.py::test_check_wazuh_manager_authd PASSED    [  5%]
    test_installation_assistant.py::test_check_wazuh_manager_db PASSED       [ 11%]
    test_installation_assistant.py::test_check_wazuh_manager_execd PASSED    [ 17%]
    test_installation_assistant.py::test_check_wazuh_manager_analysisd PASSED [ 23%]
    test_installation_assistant.py::test_check_wazuh_manager_syscheckd PASSED [ 29%]
    test_installation_assistant.py::test_check_wazuh_manager_remoted PASSED  [ 35%]
    test_installation_assistant.py::test_check_wazuh_manager_logcollec PASSED [ 41%]
    test_installation_assistant.py::test_check_wazuh_manager_monitord PASSED [ 47%]
    test_installation_assistant.py::test_check_wazuh_manager_modulesd PASSED [ 52%]
    test_installation_assistant.py::test_check_wazuh_manager_apid PASSED     [ 58%]
    test_installation_assistant.py::test_check_filebeat_process PASSED       [ 64%]
    test_installation_assistant.py::test_check_indexer_process PASSED        [ 70%]
    test_installation_assistant.py::test_check_indexer_cluster_status_not_red PASSED [ 76%]
    test_installation_assistant.py::test_check_indexer_cluster_status_not_yellow PASSED [ 82%]
    test_installation_assistant.py::test_check_wazuh_api_status PASSED       [ 88%]
    test_installation_assistant.py::test_check_log_errors FAILED             [ 94%]
    test_installation_assistant.py::test_check_alerts PASSED                 [100%]
  
    =================================== FAILURES ===================================
    ____________________________ test_check_log_errors _____________________________
  
        @pytest.mark.wazuh
        def test_check_log_errors():
            found_error = False
            exceptions = [
                'WARNING: Cluster error detected',
                'agent-upgrade: ERROR: (8123): There has been an error executing the request in the tasks manager.',
                "ERROR: Could not send message through the cluster after '10' attempts"
  
            ]
  
            with open('/var/ossec/logs/ossec.log', 'r') as f:
                for line in f.readlines():
                    if 'ERROR' in line:
                        if not any(exception in line for exception in exceptions):
                            found_error = True
                            break
    >       assert found_error == False, line
    E       AssertionError: 2024/09/16 09:14:54 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
    E
    E       assert True == False
    E         +True
    E         -False
```

I have observed the following:
- The error is not related to the system, as sometimes the error is generated and sometimes not (in the same system)
- The error is not related to the worker or master node. Sometimes the error is generated in the master node, and sometimes in the worker nodes.
- I tried to reproduce this manually without success.
- The error seems to be random

Now I'm trying to get a test with the failure state and enter to the environment to investigate the logs and the configuration.
