### ISSUE TITLE
Support new stage RC 1 for 4.8.2 in wazuh-installation-assistant repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-installation-assistant#25]
## Description

This issue attempts to support a new stage RC 1 for 4.8.2 in the wazuh-installation-assistant repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.2 (if applicable).
- [ ] Bump revision for branch 4.8.2 on wazuh-installation-assistant repository.
- [ ] Create tag v4.8.2-rc1 from branch 4.8.2 on wazuh-installation-assistant repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-installation-assistant/releases/tag/v4.8.2-rc1.
