### ISSUE TITLE
Avoid failed workflow if a pytest fails

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-installation-assistant#47]
## Description

We want to modify the Python test migrated in #20. In the Python test, if a pytest function fails, the complete task fails. For example, in the following GHA, the workflow fails because of a failed pytest: https://github.com/wazuh/wazuh/issues/25534

Although this behavior is correct, we want to make the workflow finish with other success, rather than fail in this kind of case. It seems that there are more options rather than `success` or `failure` in GitHub Actions, something like a `warning` exit code.

## Tasks

- [x] Decide the workflow exit status when a pytest fails
- [x] Apply the change
- [x] Validate the new behavior

**Comment by fcaffieri** [comment]
### Update report

After discussing the scope of the issue with the team, it was decided to generate 2 types of outputs:
1. Warning: Failure in Wazuh tests
2. Error: Failure in the installation wizard
This is because what is being tested in the test is the installation wizard and not detecting bugs in Wazuh
We will work on implementing these situations.

**Comment by fcaffieri** [comment]
### Update report

After implementing the error handler for workflows, it was detected that GitHub actions only support 2 output values:
- 0: All steps were executed correctly and the action is marked as green
- 1: Some steps failed, it is marked as red and the entire action failed.

Based on this premise, a solution was implemented where if the test of the Wazuh installation tools fails, the entire test is reported as failed. On the contrary, if only the test of the Wazuh components fails, the test is reported as successful (since the objective of the test is to validate the installation tools and not the functionality of Wazuh). Still, warnings are left in the component testing step, for later information to the responsible team.

### Improvements

Additionally, bugs on the installation wizards were fixed, and the products of the migration to 5.0.0.
Finally, an improvement was incorporated where if a crucial step fails, the execution of the remaining steps is interrupted, since the test is considered failed.

### Tests

#### Installation Wizard (Distributed)

- Stop execution of steps on failures:
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12518212911/job/34920285045
![Image](https://github.com/user-attachments/assets/dac5f170-9414-4ae6-bf1d-95265efde1ac)

https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12518291928/job/34920498369
![Image](https://github.com/user-attachments/assets/7fee465b-5083-4b4d-869c-eda86093c1c8)
![Image](https://github.com/user-attachments/assets/6022c222-afa6-4fd9-b640-4b2b32110a77)

- Bug fixed in the installation wizard
![Image](https://github.com/user-attachments/assets/03a02b94-359e-4cde-8670-a17762380cd2)
![Image](https://github.com/user-attachments/assets/eb4bbe65-e329-4397-a3bd-f0aa321aa599)

- All test works successfully
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12518596246/job/34921311838
![Image](https://github.com/user-attachments/assets/7370b557-4cac-4231-bdb3-57d66de60aa2)

**Comment by fcaffieri** [comment]
### Update report

Working on fixing the AIO install assistant:

![Image](https://github.com/user-attachments/assets/e457f716-c5bd-4f77-b3a1-718702de68ea)

**Comment by fcaffieri** [comment]
### Update report

#### Test AIO


- Stop execution of steps on failures:
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12519625965/job/34923983400
![Image](https://github.com/user-attachments/assets/75cf02d5-f9d1-4654-aca7-338e4eb11e4d)

- Bug fixed in the installation wizard
![Image](https://github.com/user-attachments/assets/d4bf3dc1-29d2-43c1-b3b6-b1c48ea6861a)
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12520456213/job/34926149965

- All test works successfully
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12520456213/job/34926149965

- Component test fail - Test installation passed
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12520573392
