### ISSUE TITLE
Support new stage RC 1 for 4.9.1 in wazuh-installation-assistant repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-installation-assistant#67]
## Description

This issue attempts to support a new stage RC 1 for 4.9.1 in the wazuh-installation-assistant repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.1 (if applicable).
- [ ] Bump revision for branch 4.9.1 on wazuh-installation-assistant repository.
- [ ] Change `source_branch` to tag v4.9.1-rc1 in branch 4.9.1
- [ ] Create tag v4.9.1-rc1 from branch 4.9.1 on wazuh-installation-assistant repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-installation-assistant/releases/tag/v4.9.1-rc1.
- [ ] Change `source_branch` back to 4.9.1 in branch 4.9.1

**Comment by davidcr01** [comment]
This repository is not being used until 4.10.0 version.
