### ISSUE TITLE
Support new stage Alpha 1 for 4.10.0 in wazuh-installation-assistant repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-installation-assistant#68]
## Description

This issue attempts to support a new stage Alpha 1 for 4.10.0 in the wazuh-installation-assistant repository.

## Tasks

- [x] Ensure changelog is updated for 4.10.0 (if applicable).
- [ ] ~~Bump revision for branch 4.10.0 on wazuh-installation-assistant repository.~~
- [x] Change `source_branch` to tag v4.10.0-alpha1 in branch 4.10.0
- [x] Create tag v4.10.0-alpha1 from branch 4.10.0 on wazuh-installation-assistant repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-installation-assistant/releases/tag/v4.10.0-alpha1.
- [x] Change `source_branch` back to 4.10.0 in branch 4.10.0

**Comment by Enaraque** [comment]
LGTM!
